spring.application.name=sub_agent_image
server.port= 8086
image.model.name= gpt-image-1
logging.level.org.springframework.ai= DEBUG
spring.ai.openai.api-key= ${OPENAI_API_KEY}
spring.ai.openai.embedding.model= text-embedding-3-large
spring.ai.openai.responses.options.model= gpt-5.1
spring.ai.openai.chat.enabled= true
spring.ai.openai.chat.options.model= gpt-5.1
spring.ai.openai.base-url= https://api.openai.com/
spring.ai.openai.image.options.size=1024x1024
spring.ai.openai.chat.options.temperature=1.0
spring.ai.openai.image.options.quality=medium
event.name.image= new-image

app.frontend.url= http://localhost:4200